export const Login = 'Login'
export const LoginFail = 'LoginFail'
export const Register = 'Register'
export const RegisterFail = 'RegisterFail'
export const EditUserSuccess = 'EditUserSuccess'
export const EditUserFail = 'EditUserFail'