export const createIssue = 'createIssue'
export const IssueError = 'IssueError'
export const showListIssue = 'showListIssue'
export const EditIssue = 'EditIssue'
export const removeIssueSucces = 'removeIssueSucces'
export const AddIssueSuccess = 'AddIssueSuccess'