export const createProject = 'createProject'
export const projectError = 'projectError'
export const getAllList = 'getAllList'
export const addSuccess = 'addSuccess'
export const getInfoSuccess = 'getInfoSuccess'
export const findProjectSuccess = 'findProjectSuccess'
export const viewListIssuesInProjectSuccess = 'viewListIssuesInProjectSuccess'