export const createSprint = 'createSprint'
export const errorSprint = 'errorSprint'
export const showListSprint = 'showListSprint'
export const deleteSprintSuccess = 'deleteSprintSuccess'
export const AddSuccess = 'AddSuccess'