export const AddUserSuccess = 'AddUserSuccess'
export const ErrorUser = 'ErrorUser'
export const GetListUser = 'getListUser'
export const FindUserLikeId = 'FindUserLikeId'
export const findUserLikeEmail = 'findUserLikeEmail'